// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VedAstro.Data;

#nullable disable

namespace VedAstro.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718192641_AddChatTables")]
    partial class AddChatTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VedAstro.Library.AddressGeoLocationEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("address_geo_location", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.AnonymousIpCallRecordEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("anonymous_ip_call_records", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.BodyInfoDatasetEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("body_info_dataset", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.CallInfoStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("call_info_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.CallStatusEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("call_tracker", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.ChatMessageEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<int>("MessageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.CoordinatesGeoLocationEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("coordinates_geo_location", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.GeoLocationTimezoneEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimezoneText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("geo_location_timezone", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.GeoLocationTimezoneMetadataEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("DaylightSavings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Daylight_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISO_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandardOffset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Standard_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimezoneText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("geo_location_timezone_metadata", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.IpAddressGeoLocationEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("ip_address_geo_location", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.IpAddressGeoLocationMetadataEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("AsnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsAnonymous")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsBogon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsDatacenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsKnownAbuser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsKnownAttacker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsProxy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsThreat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimezoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimezoneOffset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("ip_address_geo_location_metadata", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.IpAddressStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("CallsPerDay")
                        .HasColumnType("double precision");

                    b.Property<double>("CallsPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("CallsPerMinute")
                        .HasColumnType("double precision");

                    b.Property<double>("CallsPerMonth")
                        .HasColumnType("double precision");

                    b.Property<double>("CallsPerSecond")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("PerDayTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PerHourTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PerMinuteTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PerMonthTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PerSecondTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("ip_address_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.LifeEventRow", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("life_event_list", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.MarriageInfoDatasetEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("marriage_info_dataset", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.OpenAPIErrorBookEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("open_api_error_book", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.PersonListEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("BirthTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("person_list", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.PersonNameEmbeddingsEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Embeddings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("person_name_embeddings", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.PersonShareRow", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("person_share_list", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.PresetQuestionEmbeddingsEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Embeddings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("preset_question_embeddings", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.RawRequestStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Accept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcceptCharset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcceptEncoding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcceptLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Authorization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CacheControl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentLength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentMD5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cookie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IfMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IfModifiedSince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IfNoneMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IfRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IfUnmodifiedSince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxForwards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pragma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProxyAuthorization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaArch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaFullVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaPlatform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecChUaPlatformVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchDest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchReferer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecFetchUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Upgrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Warning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XAzureClientIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XForwardedFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XForwardedHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XForwardedProto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XRealIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("raw_request_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.RequestUrlStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("CallCount")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("request_url_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.SearchAddressGeoLocationEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("search_address_geo_location", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.SubscriberCallRecordEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<int>("CallCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("subscriber_call_records", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.SubscriberStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("CallCount")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("subscriber_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.UserAgentStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("CallCount")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("user_agent_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.UserDataListEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("user_data_list", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.WebPageStatisticEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<double>("CallCount")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("web_page_statistic", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.WebsiteDebugLogEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("website_debug_log", (string)null);
                });

            modelBuilder.Entity("VedAstro.Library.WebsiteErrorLogEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("RowKey")
                        .HasColumnType("text")
                        .HasColumnName("row_key");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartitionKey", "RowKey");

                    b.ToTable("website_error_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
